# Generated by Django 4.2.18 on 2025-03-23 22:37

import api.models_files.event_models
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='6-30 chars. Letters, digits, underscores, hyphens, and dots only.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator(code='invalid_username', message='Usernames must only contain letters, numbers, underscores, hyphens, or dots.', regex='^[a-zA-Z0-9_.-]+$')])),
                ('first_name', models.CharField(default='first', max_length=50)),
                ('last_name', models.CharField(default='last', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=50)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('follower', models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('CreateSoc', 'Create Society'), ('UpdateSoc', 'Update Society'), ('CreateEve', 'Create Event'), ('UpdateEve', 'Update Event'), ('CreateUse', 'Create User'), ('UpdateUse', 'Update User'), ('JoinSoc', 'Join Society')], max_length=10)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('report_type', models.CharField(choices=[('Misconduct', 'Misconduct'), ('System Issue', 'System Issue'), ('Society Issue', 'Society Issue'), ('Event Issue', 'Event Issue'), ('Other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_society_officer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Bronze', max_length=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('title', models.CharField(default='default_title', max_length=20)),
                ('description', models.CharField(default='default_description', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=300)),
                ('date', models.DateField(default=api.models_files.event_models.get_date)),
                ('start_time', models.TimeField(default=api.models_files.event_models.get_time)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('location', models.CharField(default='', max_length=300)),
                ('max_capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_title', models.CharField(default='Welcome to the Universal Student Society Platform!', help_text='The title of the website introduction section.', max_length=255, verbose_name='Introduction Title')),
                ('introduction_content', models.TextField(default="This platform is designed to help student societies manage their members, share news, organize events, and much more. Whether you're a small club or a large society, we provide the tools you need to connect with your members and thrive.\n\nKey features include: membership management, event calendars, news feeds, notifications, and customizable society pages. Get started by registering your society or logging in!", help_text='The main content of the website introduction. Use newlines to separate paragraphs.', verbose_name='Introduction Content')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=30)),
                ('description', models.CharField(default='default', max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('category', models.CharField(default='General', max_length=50)),
                ('social_media_links', models.JSONField(blank=True, default=dict, help_text='Dictionary with keys: WhatsApp, Facebook, Instagram, X, Email, Other - each with a URL value')),
                ('membership_requirements', models.TextField(blank=True, null=True)),
                ('upcoming_projects_or_plans', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='society_icons/')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_societies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('CreateSoc', 'Create Society'), ('UpdateSoc', 'Update Society'), ('CreateEve', 'Create Event'), ('UpdateEve', 'Update Event'), ('CreateUse', 'Create User'), ('UpdateUse', 'Update User'), ('JoinSoc', 'Join Society')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('roles', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('social_media_links', models.JSONField(blank=True, default=dict, null=True)),
                ('membership_requirements', models.TextField(blank=True, default='')),
                ('upcoming_projects_or_plans', models.TextField(blank=True, default='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_request/')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_request', to='api.society')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=30)),
                ('description', models.CharField(default='default', max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('category', models.CharField(default='General', max_length=50)),
                ('social_media_links', models.JSONField(blank=True, default=dict, help_text='Dictionary with keys: WhatsApp, Facebook, Instagram, X, Email, Other - each with a URL value')),
                ('membership_requirements', models.TextField(blank=True, null=True)),
                ('upcoming_projects_or_plans', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='society_icons/')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_societies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('CreateSoc', 'Create Society'), ('UpdateSoc', 'Update Society'), ('CreateEve', 'Create Event'), ('UpdateEve', 'Update Event'), ('CreateUse', 'Create User'), ('UpdateUse', 'Update User'), ('JoinSoc', 'Join Society')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('roles', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('social_media_links', models.JSONField(blank=True, default=dict, null=True)),
                ('membership_requirements', models.TextField(blank=True, default='')),
                ('upcoming_projects_or_plans', models.TextField(blank=True, default='')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_request/')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_request', to='api.society')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('is_president', models.BooleanField(default=False)),
                ('is_vice_president', models.BooleanField(default=False)),
                ('is_event_manager', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='student_icons/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocietyShowreelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='society_showreel_request/')),
                ('caption', models.CharField(blank=True, default='', max_length=50)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showreel_images_request', to='api.societyrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyShowreel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='society_showreel/')),
                ('caption', models.CharField(blank=True, default='', max_length=50)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showreel_images', to='api.society')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='society_news/images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='society_news/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('Rejected', 'Rejected'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='api.society')),
            ],
            options={
                'verbose_name': 'Society News',
                'verbose_name_plural': 'Society News',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('hidden_for_students', models.ManyToManyField(blank=True, related_name='hidden_replies', to=settings.AUTH_USER_MODEL)),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='api.reportreply')),
                ('read_by_students', models.ManyToManyField(blank=True, related_name='read_report_replies', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_replies', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.adminreportrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=30)),
                ('body', models.CharField(default='', max_length=200)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('target_type', models.CharField(choices=[('society', 'Specific Society'), ('multiple_societies', 'Multiple Societies'), ('event', 'Specific Event'), ('everyone', 'Everyone'), ('student_dashboard', 'Student Dashboard')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to='api.event')),
                ('target_multiple_societies', models.ManyToManyField(blank=True, related_name='multi_society_news', to='api.society')),
                ('target_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_notifications', to='api.society')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_news_comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_news_comments', to=settings.AUTH_USER_MODEL)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.societynews')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.newscomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='hosted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.society'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.event')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events', models.ManyToManyField(blank=True, related_name='broadcasts', to='api.event')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('societies', models.ManyToManyField(blank=True, related_name='broadcasts', to='api.society')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Delete', 'Delete'), ('Approve', 'Approve'), ('Reject', 'Reject'), ('Update', 'Update'), ('Create', 'Create'), ('Reply', 'Reply')], max_length=20)),
                ('target_type', models.CharField(choices=[('Society', 'Society'), ('Student', 'Student'), ('Event', 'Event'), ('Request', 'Request')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('target_name', models.CharField(max_length=255)),
                ('target_email', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('original_data', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('CreateSoc', 'Create Society'), ('UpdateSoc', 'Update Society'), ('CreateEve', 'Create Event'), ('UpdateEve', 'Update Event'), ('CreateUse', 'Create User'), ('UpdateUse', 'Update User'), ('JoinSoc', 'Join Society')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('major', models.CharField(blank=True, default='', max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_request/')),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='attended_events',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='api.event'),
        ),
        migrations.AddField(
            model_name='student',
            name='president_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_president', to='api.society'),
        ),
        migrations.AddField(
            model_name='student',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='members', to='api.society'),
        ),
        migrations.AddField(
            model_name='societyrequest',
            name='from_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.student'),
        ),
        migrations.AddField(
            model_name='societyrequest',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_request_president', to='api.student'),
        ),
        migrations.AddField(
            model_name='societynews',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to='api.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='event_manager',
            field=models.ForeignKey(blank=True, help_text='Assigned event manager of the society', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_manager_of_society', to='api.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='president_of_society', to='api.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='society_members',
            field=models.ManyToManyField(blank=True, related_name='societies_belongs_to', to='api.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='vice_president',
            field=models.ForeignKey(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_president_of_society', to='api.student'),
        ),
        migrations.CreateModel(
            name='NewsPublicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Feedback or notes from the admin, especially for rejections', null=True)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_requests', to='api.societynews')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_news_publications', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_publication_requests', to='api.student')),
            ],
            options={
                'verbose_name': 'News Publication Request',
                'verbose_name_plural': 'News Publication Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('CreateSoc', 'Create Society'), ('UpdateSoc', 'Update Society'), ('CreateEve', 'Create Event'), ('UpdateEve', 'Update Event'), ('CreateUse', 'Create User'), ('UpdateUse', 'Update User'), ('JoinSoc', 'Join Society')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_request', to='api.event')),
                ('hosted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_request_society', to='api.society')),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='current_attendees',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
        migrations.CreateModel(
            name='DescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_requests', to='api.society')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_requests', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='AwardStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_awards', to='api.award')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_students', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='adminreportrequest',
            name='from_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.student'),
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('relevance', models.IntegerField(choices=[(1, 'Not relevant at all'), (2, 'Slightly relevant'), (3, 'Somewhat relevant'), (4, 'Very relevant'), (5, 'Extremely relevant')], default=3, help_text='How relevant was this recommendation')),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_joined', models.BooleanField(default=False, help_text='Whether the student joined the society after the recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='api.society')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='api.student')),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedback',
                'unique_together': {('student', 'society')},
            },
        ),
    ]
