# Generated by Django 5.1.5 on 2025-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_title', models.CharField(default='Welcome to the Universal Student Society Platform!', help_text='The title of the website introduction section.', max_length=255, verbose_name='Introduction Title')),
                ('introduction_content', models.TextField(default="This platform is designed to help student societies manage their members, share news, organize events, and much more. Whether you're a small club or a large society, we provide the tools you need to connect with your members and thrive.\n\nKey features include: membership management, event calendars, news feeds, notifications, and customizable society pages. Get started by registering your society or logging in!", help_text='The main content of the website introduction. Use newlines to separate paragraphs.', verbose_name='Introduction Content')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]