# Generated by Django 4.2.18 on 2025-02-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Bronze', max_length=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('title', models.CharField(default='default_title', max_length=20)),
                ('description', models.CharField(default='default_description', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AwardStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_awards', to='api.award')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_students', to='api.student')),
            ],
        ),
    ]
