# Generated by Django 4.2.18 on 2025-03-23 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='extra_modules',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='participant_modules',
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('subtitle', 'Subtitle'), ('description', 'Description'), ('image', 'Image'), ('file', 'File')], max_length=20)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='event_modules_files/')),
                ('is_participant_only', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.event')),
                ('event_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.eventrequest')),
            ],
        ),
    ]
