# Generated by Django 4.2.18 on 2025-03-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary with keys: WhatsApp, Facebook, Instagram, X, Email, Other - each with a URL value'),
        ),
    ]
