# Generated by Django 5.1.5 on 2025-03-12 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1-5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "relevance",
                    models.IntegerField(
                        choices=[
                            (1, "Not relevant at all"),
                            (2, "Slightly relevant"),
                            (3, "Somewhat relevant"),
                            (4, "Very relevant"),
                            (5, "Extremely relevant"),
                        ],
                        default=3,
                        help_text="How relevant was this recommendation",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "is_joined",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the student joined the society after the recommendation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to="api.society",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to="api.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Feedback",
                "verbose_name_plural": "Recommendation Feedback",
                "unique_together": {("student", "society")},
            },
        ),
    ]
