# Generated by Django 5.1.5 on 2025-04-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="societyrequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
