# Generated by Django 4.2.18 on 2025-03-02 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='roles',
        ),
        migrations.AddField(
            model_name='society',
            name='event_manager',
            field=models.ForeignKey(blank=True, help_text='Assigned event manager of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_manager_of_society', to='api.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='treasurer',
            field=models.ForeignKey(blank=True, help_text='Assigned treasurer of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_of_society', to='api.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='vice_president',
            field=models.ForeignKey(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_of_society', to='api.student'),
        ),
    ]
