# Generated by Django 4.2.18 on 2025-03-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='societyrequest',
            name='timetable',
        ),
    ]
