# Generated by Django 5.1.5 on 2025-03-21 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="societynews",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("PendingApproval", "Pending Approval"),
                    ("Published", "Published"),
                    ("Archived", "Archived"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NewsPublicationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Feedback or notes from the admin, especially for rejections",
                        null=True,
                    ),
                ),
                (
                    "news_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_requests",
                        to="api.societynews",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_publication_requests",
                        to="api.student",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_news_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "News Publication Request",
                "verbose_name_plural": "News Publication Requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
