# Generated by Django 5.1.5 on 2025-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspublicationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                    ("Superseded_Approved", "Superseded (Previously Approved)"),
                    ("Superseded_Rejected", "Superseded (Previously Rejected)"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
