# Generated by Django 4.2.18 on 2025-03-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='treasurer',
        ),
        migrations.AddField(
            model_name='student',
            name='is_vice_president',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='vice_president_of',
            field=models.ForeignKey(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president', to='api.student'),
        ),
        migrations.AlterField(
            model_name='society',
            name='vice_president',
            field=models.ForeignKey(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societies_as_vp', to='api.student'),
        ),
    ]
