# Generated by Django 5.1.5 on 2025-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_event_date_alter_event_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_president",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="president_of",
            field=models.ManyToManyField(
                blank=True, related_name="president", to="api.society"
            ),
        ),
    ]
