# Generated by Django 4.2.18 on 2025-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_award_awardstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='society_icons/'),
        ),
        migrations.AddField(
            model_name='society',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
