# Generated by Django 4.2.18 on 2025-03-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyrequest',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_request', to='api.society'),
        ),
    ]
