# Generated by Django 4.2.18 on 2025-03-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_society_social_media_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_societies', to='api.admin'),
        ),
    ]
