# Generated by Django 5.1.5 on 2025-03-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="societyrequest",
            name="society",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="society_request",
                to="api.society",
            ),
        ),
    ]
