# Generated by Django 5.1.5 on 2025-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_date_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='student',
            name='is_president',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='president_of',
            field=models.ManyToManyField(blank=True, related_name='president', to='api.society'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=50),
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
    ]
