# Generated by Django 5.1.5 on 2025-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_societynews_status_newspublicationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="societynews",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("PendingApproval", "Pending Approval"),
                    ("Rejected", "Rejected"),
                    ("Published", "Published"),
                    ("Archived", "Archived"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
