# Generated by Django 5.1.5 on 2025-01-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_date_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_attendees',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='attended_events',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='api.event'),
        ),
    ]
