# Generated by Django 5.1.5 on 2025-01-23 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_student_is_president_student_president_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="6-30 characters. Letters, digits, underscores, hyphens, and dots only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Usernames must only contain letters, numbers, underscores, hyphens, or dots.",
                        regex="^[a-zA-Z0-9_.-]+$",
                    ),
                ],
            ),
        ),
    ]
