# Generated by Django 5.1.5 on 2025-03-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_recommendationfeedback"),
        ("api", "0003_alter_society_approved_by"),
    ]

    operations = []
