# Generated by Django 4.2.18 on 2025-02-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_society_icon_society_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='president_of',
        ),
        migrations.AddField(
            model_name='student',
            name='president_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='api.society'),
        ),
    ]
