# Generated by Django 4.2.18 on 2025-03-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_society_vice_president_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='vice_president',
            field=models.OneToOneField(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_of_society', to='api.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vice_president_of',
            field=models.OneToOneField(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_vice_president', to='api.society'),
        ),
    ]
