# Generated by Django 4.2.18 on 2025-01-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_current_attendees_event_max_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attended_events',
        ),
        migrations.AddField(
            model_name='student',
            name='is_president',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='president_of',
            field=models.ManyToManyField(blank=True, related_name='president', to='api.society'),
        ),
    ]
