# Generated by Django 5.1.5 on 2025-01-24 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisor",
            name="societies",
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="president_of",
            field=models.ManyToManyField(
                blank=True, related_name="presidents", to="api.society"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="6-30 chars. Letters, digits, underscores, hyphens, and dots only.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Usernames must only contain letters, numbers, underscores, hyphens, or dots.",
                        regex="^[a-zA-Z0-9_.-]+$",
                    ),
                ],
            ),
        ),
    ]
