# Generated by Django 4.2.18 on 2025-03-12 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_society_vice_president_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_vice_president',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vice_president_of',
        ),
        migrations.AddField(
            model_name='adminreportrequest',
            name='is_from_society_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='society',
            name='vice_president',
            field=models.ForeignKey(blank=True, help_text='Assigned vice-president of the society', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_of_society', to='api.student'),
        ),
    ]
