# Generated by Django 4.2.18 on 2025-02-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_president_of_student_president_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('CreateSoc', 'Create Society'), ('UpdateSoc', 'Update Society'), ('CreateEve', 'Create Event'), ('UpdateEve', 'Update Event'), ('CreateUse', 'Create User'), ('UpdateUse', 'Update User')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('report_type', models.CharField(choices=[('Misconduct', 'Misconduct'), ('System Issue', 'System Issue'), ('Society Issue', 'Society Issue'), ('Event Issue', 'Event Issue'), ('Other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
