# Generated by Django 4.2.18 on 2025-03-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_is_vice_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_vice_president',
            field=models.BooleanField(default=False),
        ),
    ]
