# Generated by Django 5.1.5 on 2025-01-16 13:36

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='event',
            name='hosted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='societies.society'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='societies.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='societies.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_societies', to='societies.advisor'),
        ),
        migrations.AddField(
            model_name='society',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='society', to='societies.student'),
        ),
        migrations.AddField(
            model_name='society',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='society',
            name='roles',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='society',
            name='society_members',
            field=models.ManyToManyField(blank=True, related_name='societies_belongs_to', to='societies.student'),
        ),
    ]
