# Generated by Django 5.1.5 on 2025-01-16 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='6-30 characters. Letters, digits, underscore, hyphen, and dots only.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator(code='invalid_username', message='Usernames must only contain letters, numbers, underscore, hyphen, and dots.', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
    ]
