# Generated by Django 5.1.5 on 2025-01-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_alter_user_username_user_unique_username'),
        ('societies', '0002_event_date_event_description_event_duration_and_more'),
    ]

    operations = [
    ]
