services:
  backend:
    environment:
      - DJANGO_SECRET_KEY=dev-key
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"

  frontend:
    environment:
      - VITE_API_URL=localhost:8000
      - VITE_APP_VERSION=1.0.0
    ports:
      - "5173:80"

  traefik:
    command:
      - "--log.level=DEBUG"
