from api.management.commands.seeding.society_generator import RandomSocietyDataGenerator
from api.management.commands.seeding.student_generator import RandomStudentDataGenerator
from api.management.commands.seeding.event_generator import RandomEventDataGenerator
from api.management.commands.seeding.comment_generator import RandomCommentDataGenerator
from api.management.commands.seeding.admin_generator import AdminGenerator