name: Django CI/CD

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up NLTK Data Directory
        run: mkdir -p /home/runner/nltk_data
      
      - name: Cache NLTK Data
        uses: actions/cache@v3
        with:
          path: /home/runner/nltk_data
          key: ${{ runner.os }}-nltk-data
      
      - name: Download NLTK punkt tokenizer
        working-directory: backend
        run: python -m nltk.downloader -d /home/runner/nltk_data punkt
      
      - name: Run Tests
        working-directory: backend
        env:
          NLTK_DATA: /home/runner/nltk_data
          PYTHONPATH: ${{ github.workspace }}/backend
        run: python manage.py test