name: Django CI/CD

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Download NLTK punkt tokenizer
      working-directory: backend
      env:
        NLTK_DATA: /home/runner/nltk_data
      run: |
        mkdir -p /home/runner/nltk_data
        python3 -m nltk.downloader -d /home/runner/nltk_data punkt

    - name: Run Tests
      working-directory: backend
      env:
        NLTK_DATA: /home/runner/nltk_data
      run: |
        python3 manage.py test