name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via Makefile
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_SSH_HOST }} << 'EOF'
            set -e
            cd /home/user/app

            echo "Pulling latest code..."
            git pull origin main

            echo "Writing .env.prod..."
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env.prod
            echo "DJANGO_DEBUG=False" >> .env.prod
            echo "VITE_API_URL=https://infiniteloop.space" >> .env.prod

            echo "Starting production containers..."
            make docker-up-prod
          EOF